version: "3.8"
services:
  app:
    image: cogvideo
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9.13}
    environment:
      SAT_HOME: /work/pretrained
    network_mode: host
    tty: true
    volumes:
      - ${PWD}:/work
    working_dir: /work
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
